# -*- coding: utf-8 -*-
"""qrcode erstellen

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aOfYe4jtpH4HFwkFkErGEN2ip5FI-vuQ

# Setup
"""

import os


if not os.path.exists('images/png'):
    os.makedirs('images/png')

if not os.path.exists('images/jpg'):
    os.makedirs('images/jpg')    

if not os.path.exists('images/gif'):
    os.makedirs('images/gif')

pip install pillow

pip install qrcode

import qrcode

"""
# QR-Code erstellen
Die fertigen Codes liegen im Ordner 'images'."""

text=(input('Eingabe: '))

input_data = text

dn=(input('Name der Datei (OHNE DATEITYP!):  '))

print('-------------------------------------------------------------')
print(text,'wird als ',dn,'_qr gespeichert.')
print('-------------------------------------------------------------')

qr = qrcode.QRCode(
        version=5,
        box_size=10,
        border=5)
qr.add_data(input_data)
qr.make(fit=True)

img = qr.make_image(fill='black', back_color='white')

img.save('images/png/'+dn+'_qr.png')
img.save('images/jpg/'+dn+'_qr.jpg')
img.save('images/gif/'+dn+'_qr.gif')

print('-------------------------------------------------------------')
print('gespeichert als: ')
print('images/png/'+dn+'_qr.png')
print('images/jpg/'+dn+'_qr.jpg')
print('images/gif/'+dn+'_qr.gif')
print('-------------------------------------------------------------')