# -*- coding: utf-8 -*-
"""qrcode_erstellen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dGjMZK1i1tGo6kNlFac-VRrS2XmEA4Yh

# Setup
"""

import os

if not os.path.exists('out/images/png'):
    os.makedirs('out/images/png')

if not os.path.exists('out/images/jpg'):
    os.makedirs('out/images/jpg')    

if not os.path.exists('out/images/gif'):
    os.makedirs('out/images/gif')

if not os.path.exists('out/audio/mp3'):
    os.makedirs('out/audio/mp3')

if not os.path.exists('out/audio/wav'):
    os.makedirs('out/audio/wav')

if not os.path.exists('out/audio/ogg'):
    os.makedirs('out/audio/ogg')    

if not os.path.exists('out/text/txt'):
    os.makedirs('out/text/txt')

pip install pillow

pip install qrcode

import qrcode

"""#QR-Code erstellen
Die fertigen Codes liegen im Ordner 'out/images'.
"""

text=(input('Eingabe: '))

input_data = text

dn=(input('Name der Datei (OHNE DATEITYP!):  '))

print('-------------------------------------------------------------')
print(text,'wird als ',dn,'_qr gespeichert.')
print('-------------------------------------------------------------')

qr = qrcode.QRCode(
        version=10,
        box_size=2,
        border=5)
qr.add_data(input_data)
qr.make(fit=True)

img = qr.make_image(fill='black', back_color='white')

img.save('out/images/png/'+dn+'_qr.png')
img.save('out/images/jpg/'+dn+'_qr.jpg')
img.save('out/images/gif/'+dn+'_qr.gif')

print('-------------------------------------------------------------')
print('Images gespeichert als: ')
print('out/images/png/'+dn+'_qr.png')
print('out/images/jpg/'+dn+'_qr.jpg')
print('out/images/gif/'+dn+'_qr.gif')
print('-------------------------------------------------------------')

"""

# Audio
Die fertigen Audios liegen im Ordner 'out/audio'"""

pip install gTTS

from gtts import gTTS 
import os
from io import BytesIO

language='de'

tts = gTTS(text,
          lang=language,
          slow=False,
          lang_check=True,

          )
tts.save('out/audio/mp3/'+dn+'_qr.mp3')
tts.save('out/audio/wav/'+dn+'_qr.wav')
tts.save('out/audio/ogg/'+dn+'_qr.ogg')

print('-------------------------------------------------------------')
print('Audios gespeichert als: ')
print('out/audio/mp3/'+dn+'_qr.mp3')
print('out/audio/wav/'+dn+'_qr.wav')
print('out/audio/ogg/'+dn+'_qr.ogg')
print('-------------------------------------------------------------')

"""# Text   *noch leer!*"""

